### PR TITLE
Make module executable - addition for #253

### PR DESCRIPTION
**Pull request by Lcrs123**
Hi, I've added a `__main__.py` file to make the module executable, as requested in Issue #253 .

It uses Json files instead of YML as requested in the issue, since there is no built-in library for YML parsing and I didn't want to add another package requirement.

The usage is:

`python -m docxtpl template_path json_path output_filename`

Running:
`python -m docxtpl -h` or `python -m docxtpl --help` returns the following help message:

> usage: docxtpl template_path json_path output_filename
> 
> Make docx file from existing template docx and json data.
> 
> positional arguments:
>   template_path    The path to the template docx file.
>   json_path        The path to the json file with the data.
>   output_filename  The filename to save the generated docx.
> 
> optional arguments:
>   -h, --help       show this help message and exit

If the output file already exists, it will ask for confirmation before overwriting.

Successfully creating the file returns a confirmation message and exits the program.

Please let me know if there is anything wrong with my PR, this is the first time I'm contributing to someone else's project, so sorry in advance if I didn't follow expected procedure.

### CODE REVIEW

**Comment by elapouya** [comment]
Very good idea. 
I have to check there is no regression
a test for this new feature is missing in tests/

**Comment by Lcrs123** [comment]
I'm not quite sure I understood how you're running your tests, but I added a `main.py` to tests, together with a test template and json file for running it.

**Comment by elapouya** [comment]
I added --quiet option, renamed and modified test and finally updated documentation, please could you try ?

**Comment by Lcrs123** [comment]
Sorry for the delay, I tried the package now with all your changes, and there is a typo in `__main__.py` that was made on [this commit](https://github.com/elapouya/python-docx-template/commit/541d5ce7cbeaa0341ca66ba22b9d0cd319122c4e#diff-779b2a91c6128513169cf2cfa72d3230aeddff0d3c0cb34a95627de0003947faR127)

I commented the line with the typo there. Not sure if I can fix it myself here since you the PR is already merged and closed.

**Comment by elapouya** [comment]
I fixed the typo and released 0.14.2 docxtpl package

**Comment by Lcrs123** [comment]
Everything seems to be working now!

**Comment by elapouya** [comment]
Of course you can :)

**Pull request merged**
