### PR TITLE
UnicodeDecodeError

### PR DESCRIPTION
**Pull request by roxmiv**

### CODE REVIEW

**Comment by elapouya** [comment]
Hello,

Did you tried to run your code when encoding=None ??

**Comment by roxmiv** [comment]
in real, no) I just tried without encoding (and have UnicodeDecodeError) and then with utf8 (and it works)

**Comment by elapouya** [comment]
May be the default value in __init__ should not be 'None' but 'utf-8'

**Comment by roxmiv** [comment]
Maybe you are right. Will u fix it by yourself?

**Comment by elapouya** [comment]
yes

**Comment by roxmiv** [comment]
Thank you

**Comment by elapouya** [comment]
Could you give your test case where you have an "UnicodeDecodeError" ?
(your template docx and the context dict you used)

**Comment by roxmiv** [comment]
[test_tpl.docx](https://github.com/elapouya/python-docx-template/files/361160/test_tpl.docx)

And the code:
# -*- coding: utf-8 -*-

from docxtpl import DocxTemplate

doc = DocxTemplate('test_tpl.docx')
context = {'name': 'Ilya'}
doc.render(context)
doc.save('test.docx')

**Comment by elapouya** [comment]
I pushed a new version, I preferred to add an encoding autodetection method.
Please check it.

**Comment by maitscha** [comment]
Hi!

I had the same UnicodeDecodeError. My quick-fix was to encode the XML as UTF-8: `self.docx._part._rels[relKey]._target._blob = xml.encode('utf-8')`, but your solution seams much more cleaner. I tested your latest commit from master and in my case it fixes the problem.

**Comment by elapouya** [comment]
Fixed in latest docxtpl version

**Pull request closed without merging**
