### PR TITLE
Update richtext.py

### PR DESCRIPTION
**Pull request by sailingnn**
add support for eastAsia fonts in RichText

### CODE REVIEW

**Comment by elapouya** [comment]
Thank you for your PR, but I cannot merge it : it is too specific to eastAsia : it should work with all other regions. May be I have to create a specific syntax...
Could you give one working example  (template + python code) ?

**Comment by sailingnn** [comment]
Hi Eric,


First of all, thank you sooooo much for all your work!&nbsp;


Let me explain the eastAsia thing. Without this, everything in English works fine but with Chinese, it does not. For example, if I want a Microsoft YaHei font，which belongs to eastAsia fonts, with my richtext part, it does not change the font.



I've attached the template and python code to the attachment. And below are detail explanations with pictures.




This picture is what it should be.



And This picture is what it does with your original program. It works fine for Engligh, but not for Chinese characters.





Hope I've fully explained the situation.




Best regards,
Dongfang Song




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "elapouya/python-docx-template"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月2日(星期二) 晚上9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [elapouya/python-docx-template] Update richtext.py (PR #452)





 
Thank you for your PR, but I cannot merge it : it is too specific to eastAsia : it should work with all other regions. May be I have to create a specific syntax...
 Could you give one working example  (template + python code) ?

**Comment by elapouya** [comment]
Hello,

The attachments  and images are not available when transmitted by email, you have to go to github interface and drag&drop them I think.

**Comment by sailingnn** [comment]
My fault. I've added a template and python code. I tested them on the Windows system.
This picture is what it should be.
[image](https://github.com/sailingnn/sailingnn.github.io/blob/master/images/eastAsia.png)

**Comment by elapouya** [comment]
I modified your code to make it more generic. There is a specific syntax for regional fonts : 
Have a look at tests/richtext_eastAsia.py

Please could you confirm it works your side ?

**Comment by sailingnn** [comment]
Yeah, it works! Thanks again for your work!

**Pull request merged**
